# Local Environment Configuration
# This file contains local development settings for Event Hub

spring:
  profiles:
    active: local
  
  datasource:
    url: jdbc:mysql://localhost:3306/webdiario_event_hub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root

server:
  port: 8082
  servlet:
    context-path: /api/event-hub

# AWS Configuration - Local Environment (LocalStack)
aws:
  region: us-east-1
  access-key: localstack
  secret-key: localstack
  sqs:
    endpoint: http://localhost:4566
    queues:
      user-events: webdiario-user-events
      system-events: webdiario-system-events
      notification-events: webdiario-notification-events
  sns:
    endpoint: http://localhost:4566
    topics:
      user-notifications: webdiario-user-notifications
      system-alerts: webdiario-system-alerts
      audit-logs: webdiario-audit-logs

# Event Hub Configuration - Local Environment
event-hub:
  batch-size: 50
  retry-attempts: 2
  retry-delay: 500
  dead-letter-queue: webdiario-dlq-local
  event-retention-days: 7
  max-event-size: 524288  # 512KB for local testing

# Logging Configuration - Local Environment
logging:
  level:
    com.webdiario.eventhub: DEBUG
    org.springframework.cloud.aws: DEBUG
    software.amazon.awssdk: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Additional Local Settings
app:
  environment: local
  debug: true
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
